# Site settings
title: Samuel Hobl
name: Samuel Hobl
email: "samuel.hobl (at) gmail (dot) com" 
description: > # this means to ignore newlines until "baseurl:"
  This site is about me and maybe you. 
  At least in an other parallel universe / simulation for sure.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://namjul.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ["node_modules", "_css", "package.json"]
collections:
  projects:
    output: true

# Prose settings
prose:
  rooturl: '_projects'
  siteurl: 'http://namjul.github.io/'
  relativeLinks: 'http://namjul.github.io/links.jsonp'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_css
    - /css
    - /_includes
    - package.json
    - links.jsonp
    - feed.xml
  metadata:
    _projects:
      - name: "category"
        field:
          element: "hidden"
          value: "project"
      - name: "layout"
        field:
          element: "hidden"
          value: "project"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "cover"
        field:
          element: "text"
          label: "Cover image"
          value: ""
